### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by ismailmayat** [leekelleher/umbraco-ditto-labs#5]
I am having the following issue 

https://our.umbraco.org/projects/developer-tools/ditto/ditto-feedback/76340-ditto-performance

On my parent model I do not have any properties which reference the children however I am getting performance issues.  If take out ditto ModelFactory performance is back to normal.  Any ideas?

Cheers

Ismail

**Comment by leekelleher** [comment]
@ismailmayat By design (in Umbraco core) the ModelFactory is called whenever an `IPublishedContent` object is requested, so with the Ditto ModelFactory implementation if the mapping is heavy then there'll be a performance hit.  Especially if there are a lot of child nodes to map.

If you are mapping child nodes, the way around it is to mark your POCO model's property as `virtual`, that will enable the lazy-loading feature.

Of course, the logic will still need to run when first requested, but delayed from app-startup.

I hope this helps?
(otherwise my recommendation is not to use Ditto ModelFactory in a production scenario - I find it difficult to offer community support for it)
